version: '3.7'
services:
  nginx:
    image: nginx:latest
    ports:
      - {{cookiecutter.port}}:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - 6379:6379

  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER={{cookiecutter.postgres_user}}
      - POSTGRES_PASSWORD={{cookiecutter.postgres_password}}
      - TZ=America/Mexico_City
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data:cached
  
  worker:
    build:
      context: backend
      dockerfile: Dockerfile
    command: celery --app app.tasks worker --loglevel=DEBUG -Q main-queue -c 1
    depends_on:
      - "redis"

  flower:  
    image: mher/flower:0.9.7
    command: celery flower --broker=redis://redis:6379/0 --port=5555
    ports:  
      - 5555:5555
    depends_on:
      - "redis"

  backend:
    build: 
      context: backend
      dockerfile: Dockerfile
    command: python app/main.py
    tty: true
    volumes:
      - ./backend:/app/:cached
      - ./.docker/.ipython:/root/.ipython:cached
    environment:
      PYTHONPATH: .
      DATABASE_URL: 'postgresql://{{cookiecutter.postgres_user}}:{{cookiecutter.postgres_password}}@postgres:5432/{{cookiecutter.postgres_user}}'
    depends_on:
      - "postgres"

volumes:
  db-data:
